name: vcpkg test - windows

on: [pull_request]

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: windows-latest
    env:
      VK_VERSION: 1.2.162.1
      PreferredToolArchitecture: x64
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
          architecture: x64
      - uses: seanmiddleditch/gha-setup-vsdevenv@master
      - name: Get software versions please
        run: |
          cmake --version
          git --version
          python --version
          cl.exe
      - name: toml
        run: pip3 install toml
      - name: setup environment vars
        run: |
             export VULKAN_SDK=$PWD/$VK_VERSION
             echo "VULKAN_SDK=$VULKAN_SDK" >> $GITHUB_ENV
             mkdir builddir
      - name: cache -- VULKAN_SDK
        id: cachedvulkan
        uses: actions/cache@v2
        with:
          path: ${{ env.VULKAN_SDK }}
          key: ${{ env.VULKAN_SDK }}-windows-vulcansdk
      - name: cache -- builddir/vcpkg
        uses: actions/cache@v2
        with:
          path: builddir/vcpkg
          key: ${{ github.head_ref }}-windows-builddir-vcpkg
      - name: Download Vulkan SDK.
        if: steps.cachedvulkan.outputs.cache-hit != 'true'
        shell: powershell
        run: wget -O VulkanSDK-${{env.VK_VERSION}}-Installer.exe https://sdk.lunarg.com/sdk/download/${{env.VK_VERSION}}/windows/VulkanSDK-${{env.VK_VERSION}}-Installer.exe?Human=true
      - name: Extract and prune Vulkan SDK
        if: steps.cachedvulkan.outputs.cache-hit != 'true'
        run: |
          7z x -aoa ./VulkanSDK-${{env.VK_VERSION}}-Installer.exe -o $VULKAN_SDK
          du -hs $VULKAN_SDK
          rm -rf $VULKAN_SDK/{Samples,Third-Party,Tools,Tools32,Bin32,Lib32}
          du -hs $VULKAN_SDK
          df -h
      - name: Build
        run: |
          pushd builddir
          cmake -GNinja -DVCPKG_ROOT=$PWD/vcpkg -DCMAKE_BUILD_TYPE=Release ..
          ninja
          popd
