name: vcpkg test - windows

on: [pull_request]

defaults:
  run:
    shell: bash

jobs:
  build:
    environment: test
    runs-on: windows-latest
    env:
      PreferredToolArchitecture: x64
      CXX: cl.exe
      CC: cl.exe
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
          architecture: x64
      - uses: seanmiddleditch/gha-setup-vsdevenv@master
      - uses: humbletim/setup-vulkan-sdk@v1.0.1
      - name: Get software versions please
        run: |
          echo VULKAN_SDK_VERSION=$VULKAN_SDK_VERSION
          cmake --version
          git --version
          python --version
          cl.exe
      - name: toml
        run: pip3 install toml
      - name: setup environment vars
        run: |
             echo "Python3_EXECUTABLE=$(which python)" >> $GITHUB_ENV
             mkdir builddir
      - name: cache -- builddir/vcpkg
        # uses: pat-s/always-upload-cache@v2.1.3
        uses: actions/cache@v2
        with:
          path: builddir/vcpkg
          key: 20210209-${{ github.head_ref }}-windows-builddir-vcpkg
      - name: Configure
        run: |
          cmake -DVCPKG_ROOT=vcpkg -GNinja -S. -B./builddir -DCMAKE_BUILD_TYPE=Release
      - name: Generate
        run: |
          ninja -C builddir \
            types/assets/MaterialAsset_generated.h \
            types/assets/MeshAsset_generated.h \
            types/assets/PrefabAsset_generated.h \
            types/assets/Registry_generated.h \
            types/assets/ScriptAsset_generated.h \
            types/assets/SerializedAsset_generated.h \
            types/assets/TextureAsset_generated.h \
            types/assets/types_generated.h \
            types/protocol/ClientEvent_generated.h \
            types/protocol/MeshRendererComponent_generated.h \
            types/protocol/PointLightComponent_generated.h \
            types/protocol/ScriptData_generated.h \
            types/protocol/ServerEvent_generated.h \
            types/protocol/TransformComponent_generated.h \
            types/protocol/types_generated.h \
            types/protocol/WorldEvent_generated.h
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3
      #   with:
      #     limit-access-to-actor: true
      - name: Build
        run: |
          ninja -C builddir
          ls -lrth builddir/bundler
          ls -lrth builddir/server
          ls -lrth builddir/client
