name: vcpkg test - windows

on: [pull_request]

defaults:
  run:
    shell: bash

jobs:
  build:
    environment: test
    runs-on: windows-latest
    env:
      VK_VERSION: 1.2.162.1
      PreferredToolArchitecture: x64
      CXX: cl.exe
      CC: cl.exe
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
          architecture: x64
      - uses: seanmiddleditch/gha-setup-vsdevenv@master
      - name: Get software versions please
        run: |
          cmake --version
          git --version
          python --version
          cl.exe
      - name: toml
        run: pip3 install toml
      - name: setup environment vars
        run: |
             export VULKAN_SDK=$PWD/$VK_VERSION
             echo "VULKAN_SDK=$VULKAN_SDK" >> $GITHUB_ENV
             echo "Python3_EXECUTABLE=$(which python)" >> $GITHUB_ENV
             mkdir builddir
      - name: cache -- VULKAN_SDK
        id: cachedvulkan
        #uses: actions/cache@v2
        uses: pat-s/always-upload-cache@v2.1.3
        with:
          path: ${{ env.VULKAN_SDK }}
          key: 20210209a-${{ env.VULKAN_SDK }}-windows-vulcansdk
      - name: cache -- builddir/vcpkg
        uses: pat-s/always-upload-cache@v2.1.3
        #uses: actions/cache@v2
        with:
          path: builddir/vcpkg
          key: 20210209-${{ github.head_ref }}-windows-builddir-vcpkg
      - name: Download Vulkan SDK.
        if: steps.cachedvulkan.outputs.cache-hit != 'true'
        shell: powershell
        run: |
          $ProgressPreference = 'SilentlyContinue'
          Invoke-WebRequest -Uri https://sdk.lunarg.com/sdk/download/${{env.VK_VERSION}}/windows/VulkanSDK-${{env.VK_VERSION}}-Installer.exe?Human=true -OutFile VulkanSDK-${{env.VK_VERSION}}-Installer.exe
      - name: Verify, extract and prune Vulkan SDK
        if: steps.cachedvulkan.outputs.cache-hit != 'true'
        run: |
          echo "bbeb8a97e3dabf928805bfd8ef30423fe2bc870016f2da4e17321c15c2ea2c8817ac0b98f5e7ac89a284cf3173cae43539a4aa426f0fa89b3a347d75c2e309e0 *VulkanSDK-${{env.VK_VERSION}}-Installer.exe" | \
            sha512sum --check
          7z x -aoa ./VulkanSDK-${{env.VK_VERSION}}-Installer.exe -o$VULKAN_SDK
          du -hs .
          rm -rf $VULKAN_SDK/{Samples,Third-Party,Tools,Tools32,Bin32,Lib32}
          du -hs .
          df -h
      - name: Build
        run: |
          pushd builddir
          cmake -GNinja -DVCPKG_ROOT=$PWD/vcpkg -DCMAKE_BUILD_TYPE=Release ..
          ninja
          popd
